Server:
  Port: 9876
  Host: "localhost"
Postgres:
  Host: "localhost"
  User: "arash2007mahdavi"
  Password: "@rash2007"
  Dbname: "digimovie_database"
  Port: 5432
  Sslmode: "disable" 
  MaxIdleConns: 5
  MaxOpenConns: 100
  ConnMaxLifetime: 5
Logger:
  FilePath: ./logs.log
  Encoding: json
  Level: debug
  Logger: zaplogger